# Generated by Django 6.0 on 2025-12-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=512, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaEstudante',
            fields=[
                ('pk', models.CompositePrimaryKey('area', 'estudante_utilizador_auth_user_supabase_field', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'area_estudante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=254)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('nome', models.CharField(blank=True, max_length=512, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.SmallIntegerField(blank=True, null=True)),
                ('auth_user_supabase_id', models.UUIDField(db_column='auth_user_supabase__id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('validated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curriculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaArea',
            fields=[
                ('pk', models.CompositePrimaryKey('empresa_utilizador_auth_user_supabase_field', 'area', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'empresa_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('oportunidade', models.CharField(blank=True, max_length=512, null=True)),
                ('visualizacoes', models.IntegerField(blank=True, null=True)),
                ('candidaturas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VagaArea',
            fields=[
                ('pk', models.CompositePrimaryKey('vaga_id', 'area_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vaga_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cr',
            fields=[
                ('tipo', models.SmallIntegerField(blank=True, null=True)),
                ('utilizador_auth_user_supabase_field', models.OneToOneField(db_column='utilizador_auth_user_supabase__id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service.utilizador')),
            ],
            options={
                'db_table': 'cr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('tipo', models.SmallIntegerField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=512, null=True)),
                ('website', models.CharField(blank=True, max_length=512, null=True)),
                ('utilizador_auth_user_supabase_field', models.OneToOneField(db_column='utilizador_auth_user_supabase__id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service.utilizador')),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('tipo', models.SmallIntegerField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('grau', models.CharField(blank=True, max_length=512, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('disponibilidade', models.CharField(blank=True, max_length=512, null=True)),
                ('share_aceites', models.BooleanField(blank=True, null=True)),
                ('utilizador_auth_user_supabase_field', models.OneToOneField(db_column='utilizador_auth_user_supabase__id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service.utilizador')),
            ],
            options={
                'db_table': 'estudante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrCurriculo',
            fields=[
                ('curriculo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service.curriculo')),
            ],
            options={
                'db_table': 'cr_curriculo',
                'managed': False,
            },
        ),
    ]
