# Generated by Django 6.0.2 on 2026-02-10 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accessed_by_user_id', models.UUIDField()),
                ('accessed_by_role', models.SmallIntegerField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cv_access_log',
                'managed': False,
            },
        ),
    ]
