# Generated by Django 6.0.1 on 2026-02-15 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        # CVAccessLog: managed=False — registo apenas para o sistema de
        # migrações do Django. Não cria nem altera tabelas.
        migrations.CreateModel(
            name='CVAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accessed_by_user_id', models.UUIDField()),
                ('accessed_by_role', models.SmallIntegerField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cv_access_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_user_id', models.UUIDField(db_index=True, help_text='UUID do utilizador destinatário (Supabase Auth ID)')),
                ('recipient_email', models.EmailField(help_text='Email do destinatário no momento do envio', max_length=254)),
                ('type', models.CharField(choices=[('cv_status_change', 'Alteração de estado do CV'), ('cv_feedback', 'Feedback do CV')], db_index=True, help_text='Tipo de notificação', max_length=50)),
                ('subject', models.CharField(help_text='Assunto do email enviado', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falha')], db_index=True, help_text='Estado de envio da notificação', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Mensagem de erro em caso de falha')),
                ('read', models.BooleanField(db_index=True, default=False, help_text='Se a notificação foi lida pelo utilizador')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculo', models.ForeignKey(blank=True, db_constraint=False, help_text='Currículo associado à notificação (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='service.curriculo')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
