# Generated by Django 6.0.2 on 2026-02-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_cvaccesslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crcurriculo',
            options={'managed': False, 'ordering': ['-review_date']},
        ),
    ]
